// Builds public/ from src/.  Run: node scripts/build.mjs
// Reads public config from env (or .env locally):
//   SUPABASE_URL, SUPABASE_ANON_KEY, TURNSTILE_SITE_KEY (optional)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnv } from './env.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
loadEnv(root);
const r = p => path.join(root, p);

const tpl = fs.readFileSync(r('src/template.html'), 'utf8');
const css = fs.readFileSync(r('src/leaflet.css'), 'utf8');
const geo = fs.readFileSync(r('src/bkk.min.json'), 'utf8');

const page = tpl.replace('/*__LEAFLET_CSS__*/', () => css).replace('/*__GEOJSON__*/null', () => geo);
const html = `<!doctype html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0F5A63">
<style>body{margin:0}[hidden]{display:none!important}</style>
</head>
<body>
${page}
</body>
</html>
`;

const config = {
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY || '',
  turnstileSiteKey: process.env.TURNSTILE_SITE_KEY || '',
};

fs.mkdirSync(r('public'), { recursive: true });
fs.writeFileSync(r('public/index.html'), html);
fs.writeFileSync(r('public/config.js'), `window.APP_CONFIG = ${JSON.stringify(config, null, 2)};\n`);
fs.writeFileSync(r('api/_districts.js'), `// generated by scripts/build.mjs — do not edit\nexport const DISTRICTS = ${geo};\n`);

console.log(`built public/index.html (${(html.length / 1024).toFixed(0)} KB)`);
console.log(config.supabaseUrl ? `  Supabase: ${config.supabaseUrl}` : '  Supabase: not set → local demo mode (pins stay in the browser)');
console.log(config.turnstileSiteKey ? '  Turnstile: on' : '  Turnstile: off');
